/**
 * DanceShapeLong — 25-30 min pure geometric shape dance, no text, no sprites.
 * Universal content: EN + AR + ID channels (zero language-specific content).
 *
 * Supports 8 motion primitives: BOB, SWAY, SPIN, DRIFT, PULSE, WAVE, ORBIT, BOUNCE
 * Plus: MARCH (continuous march), FADEIN / FADEOUT (appear/disappear sequentially), NONE
 *
 * Videos 1-12 of the Dancing Shapes series are generated by generate_dance_shape.py.
 */
import React from "react";
import {
  AbsoluteFill,
  Audio,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { Shape, ShapeName } from "./components/Shape";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ShapeItem {
  shape: ShapeName;
  color: string;           // hex base color
  size: number;            // px
  posX: number;            // 0–1 of width  (base center)
  posY: number;            // 0–1 of height (base center)
  seed: number;            // deterministic variation (unique per shape)
  orbitRadius?: number;    // px — if >0, orbits the block's orbitCenter; 0 = stationary
  orbitPeriodSec?: number; // seconds per full orbit (default 8)
  orbitCcw?: boolean;      // counter-clockwise (default false)
  colorOffset?: number;    // 0–1 offset into palette cycle (for staggering colors)
}

export type MotionType =
  | "BOB"     // vertical oscillation
  | "SWAY"    // horizontal oscillation
  | "SPIN"    // rotation in place
  | "DRIFT"   // Lissajous path
  | "PULSE"   // scale breathing
  | "WAVE"    // BOB with phase delay per shape
  | "ORBIT"   // circular path — per-shape orbitRadius determines individual radius
  | "BOUNCE"  // sharp-bottomed vertical bounce
  | "MARCH"   // continuous L→R march with wrap-around
  | "FADEIN"  // shapes appear sequentially + gentle drift
  | "FADEOUT" // shapes disappear sequentially + gentle drift
  | "NONE";   // stationary

export interface MotionBlock {
  startSec: number;
  endSec: number;
  motion: MotionType;
  period?: number;          // sec/cycle for BOB/SWAY/PULSE/WAVE/BOUNCE (default 3)
  amplitude?: number;       // px for movement; percent (0-100) for PULSE; deg for SPIN (default 40)
  waveDelay?: number;       // sec between shapes for WAVE (default 0.4)
  orbitCenterX?: number;    // 0–1 screen (default 0.5)
  orbitCenterY?: number;    // 0–1 screen (default 0.45)
  bobAmplitude?: number;    // secondary bob for MARCH (default 0)
  colorPalette?: string[];  // if set, shapes cycle through these colors
  colorCycleSec?: number;   // sec per color in palette (default 20)
}

export interface DanceShapeLongProps {
  shapes: ShapeItem[];
  blocks: MotionBlock[];
  bgColor: string;
  bgColorEnd?: string;  // night mode: bg gradually darkens toward this
  musicFile: string;
  volume?: number;
  nightMode?: boolean;  // gradually dims shape opacity 100%→60% over video
}

// ── Color helpers ─────────────────────────────────────────────────────────────

function hexToRgb(hex: string): [number, number, number] {
  return [
    parseInt(hex.slice(1, 3), 16),
    parseInt(hex.slice(3, 5), 16),
    parseInt(hex.slice(5, 7), 16),
  ];
}

function rgbToHex(r: number, g: number, b: number): string {
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

function lerpColor(a: string, b: string, t: number): string {
  const [r1, g1, b1] = hexToRgb(a);
  const [r2, g2, b2] = hexToRgb(b);
  return rgbToHex(
    Math.round(r1 + (r2 - r1) * t),
    Math.round(g1 + (g2 - g1) * t),
    Math.round(b1 + (b2 - b1) * t),
  );
}

function computeColor(
  shape: ShapeItem,
  shapeIdx: number,
  fSec: number,
  block: MotionBlock,
): string {
  const { colorPalette, colorCycleSec = 20 } = block;
  if (!colorPalette || colorPalette.length < 2) return shape.color;
  const offset = (shape.colorOffset ?? 0) * colorCycleSec;
  const t = (fSec + offset) % (colorCycleSec * colorPalette.length);
  const idx = Math.floor(t / colorCycleSec);
  const progress = (t % colorCycleSec) / colorCycleSec;
  return lerpColor(
    colorPalette[idx % colorPalette.length],
    colorPalette[(idx + 1) % colorPalette.length],
    progress,
  );
}

// ── Motion computation ────────────────────────────────────────────────────────

interface Transform {
  cx: number;      // absolute center X
  cy: number;      // absolute center Y
  rotation: number; // degrees
  scale: number;
  opacity: number;
}

function computeTransform(
  block: MotionBlock,
  shape: ShapeItem,
  shapeIdx: number,
  numShapes: number,
  fSec: number,
  width: number,
  height: number,
): Transform {
  const t = fSec - block.startSec;          // seconds since block start
  const blockDur = block.endSec - block.startSec;

  const period    = block.period    ?? 3;
  const amplitude = block.amplitude ?? 40;
  const baseX     = shape.posX * width;
  const baseY     = shape.posY * height;

  let cx = baseX, cy = baseY, rotation = 0, scale = 1, opacity = 1;
  const tau = 2 * Math.PI;

  switch (block.motion) {
    case "BOB":
      cy = baseY + Math.sin((t / period) * tau) * amplitude;
      break;

    case "SWAY":
      cx = baseX + Math.sin((t / period) * tau) * amplitude;
      break;

    case "SPIN":
      rotation = (t / period) * 360;
      break;

    case "DRIFT": {
      // Lissajous — non-repeating path via golden ratio frequency
      const freqX = tau / (period * 1.618);
      const freqY = tau / period;
      const ph = shape.seed * 2.1;
      cx = baseX + Math.sin(t * freqX + ph) * amplitude;
      cy = baseY + Math.sin(t * freqY + ph + 1.3) * (amplitude * 0.6);
      // Slow self-rotation while drifting
      rotation = Math.sin(t * 0.4 + shape.seed) * 15;
      break;
    }

    case "PULSE": {
      const pct = amplitude / 100;
      scale = 1 + Math.sin((t / period) * tau) * pct;
      // subtle bob while pulsing
      cy = baseY + Math.sin((t / period) * tau + 0.3) * 12;
      break;
    }

    case "WAVE": {
      const delay = block.waveDelay ?? 0.4;
      const td = t - shapeIdx * delay;
      cy = baseY + Math.sin((td / period) * tau) * amplitude;
      break;
    }

    case "ORBIT": {
      const r = shape.orbitRadius ?? 0;
      if (r <= 0) {
        // Stationary anchor — gentle pulse so it's never static
        scale = 1 + Math.sin(t * 0.8 + shape.seed) * 0.06;
      } else {
        const oPeriod = shape.orbitPeriodSec ?? 8;
        const dir = shape.orbitCcw ? -1 : 1;
        const angle = dir * (t / oPeriod) * tau + shape.seed;
        const ocx = (block.orbitCenterX ?? 0.5) * width;
        const ocy = (block.orbitCenterY ?? 0.45) * height;
        cx = ocx + Math.cos(angle) * r;
        cy = ocy + Math.sin(angle) * r * 0.6; // slightly flatten orbit
        // Small self-rotation while orbiting
        rotation = dir * (t / oPeriod) * 180;
      }
      break;
    }

    case "BOUNCE": {
      cy = baseY - Math.abs(Math.sin((t / period) * tau)) * amplitude;
      // Slight squash at bottom
      const phase = Math.abs(Math.sin((t / period) * tau));
      scale = 1 + (1 - phase) * 0.06; // squash when at ground
      break;
    }

    case "MARCH": {
      const marchPeriod = period; // seconds to traverse full screen width
      const spacing = width / numShapes;
      const startX = shapeIdx * spacing + shape.size / 2;
      const marchDist = (t / marchPeriod) * width;
      cx = ((startX + marchDist) % (width + shape.size)) - shape.size / 2;
      if (cx < -shape.size) cx += width + shape.size; // safety wrap
      cy = baseY;
      // March bob
      const bobAmp = block.bobAmplitude ?? 20;
      cy = baseY - Math.abs(Math.sin((t / (marchPeriod / numShapes)) * tau)) * bobAmp;
      // Square tilts slightly when marching
      rotation = Math.sin((t / marchPeriod) * tau * numShapes + shapeIdx) * 8;
      break;
    }

    case "FADEIN": {
      // Shapes appear one-by-one; between appearances, gentle drift
      const perShapeSec = blockDur / numShapes;
      const appearAt = block.startSec + shapeIdx * perShapeSec;
      opacity = interpolate(fSec, [appearAt, appearAt + 5], [0, 1], {
        extrapolateLeft: "clamp", extrapolateRight: "clamp",
      });
      // Drift while visible
      const ph = shape.seed * 2.1;
      const driftAmp = (amplitude > 0 ? amplitude : 80);
      cx = baseX + Math.sin(t * 0.25 + ph) * driftAmp;
      cy = baseY + Math.sin(t * 0.18 + ph + 1) * (driftAmp * 0.55);
      rotation = Math.sin(t * 0.3 + shape.seed) * 10;
      break;
    }

    case "FADEOUT": {
      const perShapeSec = blockDur / numShapes;
      const disappearAt = block.startSec + (numShapes - 1 - shapeIdx) * perShapeSec;
      opacity = interpolate(fSec, [disappearAt, disappearAt + 5], [1, 0], {
        extrapolateLeft: "clamp", extrapolateRight: "clamp",
      });
      const ph = shape.seed * 2.1;
      const driftAmp = (amplitude > 0 ? amplitude : 80);
      cx = baseX + Math.sin(t * 0.25 + ph) * driftAmp;
      cy = baseY + Math.sin(t * 0.18 + ph + 1) * (driftAmp * 0.55);
      rotation = Math.sin(t * 0.3 + shape.seed) * 10;
      break;
    }

    case "NONE":
    default:
      // Idle float — visible drift so it's never truly static
      cx = baseX + Math.sin(t * 0.55 + shape.seed) * 18;
      cy = baseY + Math.sin(t * 0.42 + shape.seed * 1.4) * 14;
      scale = 1 + Math.sin(t * 0.9 + shape.seed * 0.7) * 0.05;
      break;
  }

  return { cx, cy, rotation, scale, opacity };
}

// ── Main composition ──────────────────────────────────────────────────────────

export const DanceShapeLong: React.FC<DanceShapeLongProps> = ({
  shapes,
  blocks,
  bgColor,
  bgColorEnd,
  musicFile,
  volume = 0.2,
  nightMode = false,
}) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames, width, height } = useVideoConfig();
  const fSec = frame / fps;

  // Background color (optionally fades to darker for night mode)
  const bgProgress = bgColorEnd
    ? interpolate(fSec, [0, durationInFrames / fps], [0, 1], {
        extrapolateLeft: "clamp", extrapolateRight: "clamp",
      })
    : 0;
  const currentBg = bgColorEnd ? lerpColor(bgColor, bgColorEnd, bgProgress) : bgColor;

  // Night-mode dim: overall shape brightness 1.0 → 0.6 over the video
  const nightDim = nightMode
    ? interpolate(fSec, [0, durationInFrames / fps], [1, 0.6], {
        extrapolateLeft: "clamp", extrapolateRight: "clamp",
      })
    : 1;

  // Global fade-out last 3 seconds
  const fadeOut = interpolate(
    frame,
    [durationInFrames - fps * 3, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Find current block (last matching block wins if overlapping)
  const currentBlock =
    [...blocks].reverse().find((b) => fSec >= b.startSec && fSec < b.endSec) ??
    blocks[blocks.length - 1];

  // Block transition fade: smooth 1.5s cross-fade at block boundaries
  const blockAlpha = (() => {
    const idx = blocks.indexOf(currentBlock);
    if (idx === 0) {
      // Fade in at very start
      return interpolate(fSec, [0, 1.5], [0, 1], {
        extrapolateLeft: "clamp", extrapolateRight: "clamp",
      });
    }
    const transitionSec = blocks[idx].startSec;
    return interpolate(fSec, [transitionSec, transitionSec + 1.5], [0, 1], {
      extrapolateLeft: "clamp", extrapolateRight: "clamp",
    });
  })();

  return (
    <AbsoluteFill style={{ backgroundColor: currentBg, overflow: "hidden" }}>
      <Audio src={staticFile(`music/${musicFile}`)} volume={volume} loop />

      <AbsoluteFill style={{ opacity: fadeOut * nightDim * blockAlpha }}>
        {shapes.map((shape, i) => {
          const { cx, cy, rotation, scale, opacity } = computeTransform(
            currentBlock, shape, i, shapes.length, fSec, width, height,
          );
          const color = computeColor(shape, i, fSec, currentBlock);
          const size = shape.size;

          return (
            <div
              key={i}
              style={{
                position: "absolute",
                left: cx - size / 2,
                top: cy - size / 2,
                width: size,
                height: size,
                transform: `rotate(${rotation}deg) scale(${scale})`,
                transformOrigin: "center center",
              }}
            >
              <Shape name={shape.shape} size={size} color={color} opacity={opacity} />
            </div>
          );
        })}
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
